<html>
<head>
<title>Python Exceptions — What, Why, and How?</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">Python 异常——什么、为什么和如何？</h1>
<blockquote>原文：<a href="https://towardsdatascience.com/python-exceptions-what-why-and-how-44661cad3cd4#2022-03-31">https://towardsdatascience.com/python-exceptions-what-why-and-how-44661cad3cd4#2022-03-31</a></blockquote><div><div class="fc ie if ig ih ii"/><div class="ij ik il im in"><div class=""/><div class=""><h2 id="dff2" class="pw-subtitle-paragraph jn ip iq bd b jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke dk translated">理解 Python 中异常的工作方式以及如何正确使用它们</h2></div><figure class="kg kh ki kj gt kk gh gi paragraph-image"><div role="button" tabindex="0" class="kl km di kn bf ko"><div class="gh gi kf"><img src="../Images/2b81636e59144346101b829bd1b93a42.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*kMqnY0gWkMZjuS2o"/></div></div><p class="kr ks gj gh gi kt ku bd b be z dk translated">在<a class="ae kv" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上由<a class="ae kv" href="https://unsplash.com/@erwanhesry?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Erwan Hesry </a>拍摄的照片</p></figure><h1 id="9344" class="kw kx iq bd ky kz la lb lc ld le lf lg jw lh jx li jz lj ka lk kc ll kd lm ln bi translated">什么是例外？</h1><p id="b621" class="pw-post-body-paragraph lo lp iq lq b lr ls jr lt lu lv ju lw lx ly lz ma mb mc md me mf mg mh mi mj ij bi translated">异常就像一些恼人的朋友，在您的 Python 之旅中，您会以这样或那样的方式遇到它们。任何时候你试图做一些不守规矩的事情或者让 Python 做一些 Python 不喜欢的事情，你很可能会被移交给一些<em class="mk">异常</em>，它们会根据“冒犯”的程度停止或者只是警告你</p><blockquote class="ml"><p id="f897" class="mm mn iq bd mo mp mq mr ms mt mu mj dk translated">Python 用自己的方式告诉你，你所要求的要么无法实现，要么需要做些事情来避免将来执行失败。</p></blockquote><p id="cbec" class="pw-post-body-paragraph lo lp iq lq b lr mw jr lt lu mx ju lw lx my lz ma mb mz md me mf na mh mi mj ij bi translated">在这篇文章中，我们将深入 Python <em class="mk">异常</em>的细节。我们将学习如何处理它们，将它们理解为 Python <em class="mk">类</em>，如何基于异常类型定制我们的响应，还将知道如何创建自己的异常。</p><p id="5162" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">由于异常本身就是类，我们将使用大量对 Python 类的引用。因此，如果你需要快速复习，你可以阅读我的关于 Python 中面向对象编程的系列文章。</p><h1 id="64df" class="kw kx iq bd ky kz la lb lc ld le lf lg jw lh jx li jz lj ka lk kc ll kd lm ln bi translated">处理异常</h1><p id="1967" class="pw-post-body-paragraph lo lp iq lq b lr ls jr lt lu lv ju lw lx ly lz ma mb mc md me mf mg mh mi mj ij bi translated">异常是 Python 告诉你事情没有按计划或预期进行的方式。在交互式和特别的编码场景中，比如数据分析，我们通常不需要处理异常，因为我们在面对异常并继续前进时会修复它们。但是如果你想把你的脚本用于任何类型的自动化任务，比如一个<a class="ae kv" href="https://en.wikipedia.org/wiki/Extract,_transform,_load" rel="noopener ugc nofollow" target="_blank"> ETL </a>任务，不处理异常就像把一把上膛的枪放在无人看管的地方，对准你的脚。你永远不知道什么时候会有人给它一个晃动，无意中拍摄它！</p><blockquote class="ml"><p id="7c89" class="mm mn iq bd mo mp mq mr ms mt mu mj dk translated"><em class="mv">我们所说的</em>处理异常<em class="mv">基本上是指设置一组命令，这样如果发生</em>异常<em class="mv">，Python 就知道下一步该做什么，而不仅仅是抛出一个 fit。</em></p></blockquote><h2 id="0e77" class="ng kx iq bd ky nh ni dn lc nj nk dp lg lx nl nm li mb nn no lk mf np nq lm nr bi translated">最简单的方法</h2><p id="cb26" class="pw-post-body-paragraph lo lp iq lq b lr ls jr lt lu lv ju lw lx ly lz ma mb mc md me mf mg mh mi mj ij bi translated">为了捕获异常，我们使用了一个名为<code class="fe ns nt nu nv b">try-except</code>的代码块。我们将被怀疑是错误来源的那段代码放在<code class="fe ns nt nu nv b">try</code>块中，然后在<code class="fe ns nt nu nv b">except</code>块中捕获并设计响应。查看以下示例，其中函数<code class="fe ns nt nu nv b">calcArea</code>被定义为从用户处接收圆的<code class="fe ns nt nu nv b">radius</code>值，并返回圆的计算面积。</p><figure class="kg kh ki kj gt kk"><div class="bz fp l di"><div class="nw nx l"/></div></figure><pre class="kg kh ki kj gt ny nv nz oa aw ob bi"><span id="6989" class="ng kx iq nv b gy oc od l oe of">Area for radius 5 = 78.53999999999999</span><span id="1697" class="ng kx iq nv b gy og od l oe of">Something is wrong with a</span><span id="46a4" class="ng kx iq nv b gy og od l oe of">Area for radius 4 = 50.2656</span><span id="3137" class="ng kx iq nv b gy og od l oe of">Area for radius 8 = 201.0624</span><span id="9f19" class="ng kx iq nv b gy og od l oe of">Something is wrong with b</span><span id="f8d4" class="ng kx iq nv b gy og od l oe of">Area for radius 0 = 0.0</span></pre><p id="92c0" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">在<code class="fe ns nt nu nv b">for</code>循环中，</p><p id="bf21" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">Python 首先执行<code class="fe ns nt nu nv b">try</code>块内的<code class="fe ns nt nu nv b">calcArea()</code>。</p><ul class=""><li id="8d62" class="oh oi iq lq b lr nb lu nc lx oj mb ok mf ol mj om on oo op bi translated">它试图计算面积并将其保存到名为<code class="fe ns nt nu nv b">area</code>的变量中。</li><li id="2b24" class="oh oi iq lq b lr oq lu or lx os mb ot mf ou mj om on oo op bi translated">如果没有遇到任何异常，它打印出新创建的变量<code class="fe ns nt nu nv b">area</code>。</li><li id="91de" class="oh oi iq lq b lr oq lu or lx os mb ot mf ou mj om on oo op bi translated">但是如果它遇到了问题，它就转移到<code class="fe ns nt nu nv b">except</code>代码块。</li></ul><p id="4770" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">在<code class="fe ns nt nu nv b">except</code>代码块内，</p><ul class=""><li id="cfad" class="oh oi iq lq b lr nb lu nc lx oj mb ok mf ol mj om on oo op bi translated"><code class="fe ns nt nu nv b">Exception</code>类被捕获或存储，并被命名为<code class="fe ns nt nu nv b">e</code>，或者给它你想要的任何名字。这个命名对象随后用于访问<em class="mk">异常</em>类<em class="mk">对象</em>的元素。</li></ul></div><div class="ab cl ov ow hu ox" role="separator"><span class="oy bw bk oz pa pb"/><span class="oy bw bk oz pa pb"/><span class="oy bw bk oz pa"/></div><div class="ij ik il im in"><p id="ceeb" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">但是异常处理有什么好处呢？</p><p id="06d7" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">请注意，一旦<code class="fe ns nt nu nv b">for</code>循环获得意外值，即<code class="fe ns nt nu nv b">strings</code>，它不会中断。如果我们不处理从<code class="fe ns nt nu nv b">calcArea()</code>抛出的异常，那么<code class="fe ns nt nu nv b">for</code>循环就会在执行完第一个元素后中断。</p><p id="4071" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">🛑看你自己试试看！尝试在不使用<code class="fe ns nt nu nv b">try-except</code>的情况下在循环中运行<code class="fe ns nt nu nv b">calcArea()</code>。</p></div><div class="ab cl ov ow hu ox" role="separator"><span class="oy bw bk oz pa pb"/><span class="oy bw bk oz pa pb"/><span class="oy bw bk oz pa"/></div><div class="ij ik il im in"><h2 id="8910" class="ng kx iq bd ky nh pc dn lc nj pd dp lg lx pe nm li mb pf no lk mf pg nq lm nr bi translated">让我们稍微投入一点</h2><p id="d13d" class="pw-post-body-paragraph lo lp iq lq b lr ls jr lt lu lv ju lw lx ly lz ma mb mc md me mf mg mh mi mj ij bi translated"><code class="fe ns nt nu nv b">try-except</code>代码块有两个附加分支:<code class="fe ns nt nu nv b">else</code>和<code class="fe ns nt nu nv b">finally</code>。</p><ul class=""><li id="6468" class="oh oi iq lq b lr nb lu nc lx oj mb ok mf ol mj om on oo op bi translated"><code class="fe ns nt nu nv b">else</code>代码块只有在没有异常发生的情况下才会执行。我们可以用它以一种更简洁的方式打印出一个成功操作的定制消息——而不是把它塞在<code class="fe ns nt nu nv b">try</code>块中。</li><li id="5085" class="oh oi iq lq b lr oq lu or lx os mb ot mf ou mj om on oo op bi translated"><code class="fe ns nt nu nv b">finally</code>无论有无异常，代码块<strong class="lq ir">总是</strong>被执行。通常用于留下一个脚印以标志操作的结束。</li></ul><figure class="kg kh ki kj gt kk"><div class="bz fp l di"><div class="nw nx l"/></div></figure><pre class="kg kh ki kj gt ny nv nz oa aw ob bi"><span id="a898" class="ng kx iq nv b gy oc od l oe of">calcArea() ran successfully for 5<br/>Area for input 5 = 78.53999999999999 <br/>calcArea() run completed on 2022-03-24 10:36:49.778314<br/><br/>Something is wrong for a.<br/>Area for input a = None <br/>calcArea() run completed on 2022-03-24 10:36:49.778314<br/><br/>calcArea() ran successfully for 4<br/>Area for input 4 = 50.2656 <br/>calcArea() run completed on 2022-03-24 10:36:49.779315<br/><br/>calcArea() ran successfully for 8<br/>Area for input 8 = 201.0624 <br/>calcArea() run completed on 2022-03-24 10:36:49.779315<br/><br/>Something is wrong for b.<br/>Area for input b = None <br/>calcArea() run completed on 2022-03-24 10:36:49.779315<br/><br/>calcArea() ran successfully for 0<br/>Area for input 0 = 0.0 <br/>calcArea() run completed on 2022-03-24 10:36:49.779315</span></pre><h2 id="07cf" class="ng kx iq bd ky nh pc dn lc nj pd dp lg lx pe nm li mb pf no lk mf pg nq lm nr bi translated">更有表现力怎么样！</h2><p id="a130" class="pw-post-body-paragraph lo lp iq lq b lr ls jr lt lu lv ju lw lx ly lz ma mb mc md me mf mg mh mi mj ij bi translated">我们的<code class="fe ns nt nu nv b">try-except</code>模块告诉我们有问题，但没有告诉我们到底哪里出了问题。在本节中，我们将对此进行研究。</p><p id="2818" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">正如我们已经知道的，Python 中的异常基本上是类本身，它们还带有一些 Python 类的内置变量。在下面的例子中，我们将使用这些类属性中的一些来使错误消息更有表现力。</p><p id="32a1" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">让我们先看看例子，然后我们会回来讨论例子中使用的类属性。</p><figure class="kg kh ki kj gt kk"><div class="bz fp l di"><div class="nw nx l"/></div></figure><pre class="kg kh ki kj gt ny nv nz oa aw ob bi"><span id="1e6b" class="ng kx iq nv b gy oc od l oe of">calcArea() ran successfully for 5<br/>Area for input 5 = 78.53999999999999 <br/>calcArea() run completed on 2022-03-24 10:36:52.476687<br/><br/>Area couldn't be calculated for a.<br/>Error type: ValueError <br/>Error msg: could not convert string to float: 'a'.<br/>Area for input a = None <br/>calcArea() run completed on 2022-03-24 10:36:52.476687<br/><br/>calcArea() ran successfully for 4<br/>Area for input 4 = 50.2656 <br/>calcArea() run completed on 2022-03-24 10:36:52.476687<br/><br/>calcArea() ran successfully for 8<br/>Area for input 8 = 201.0624 <br/>calcArea() run completed on 2022-03-24 10:36:52.476687<br/><br/>Area couldn't be calculated for b.<br/>Error type: ValueError <br/>Error msg: could not convert string to float: 'b'.<br/>Area for input b = None <br/>calcArea() run completed on 2022-03-24 10:36:52.477706<br/><br/>calcArea() ran successfully for 0<br/>Area for input 0 = 0.0 <br/>calcArea() run completed on 2022-03-24 10:36:52.477706</span></pre><ul class=""><li id="21e8" class="oh oi iq lq b lr nb lu nc lx oj mb ok mf ol mj om on oo op bi translated"><code class="fe ns nt nu nv b">type(e).__name__</code>:打印出<em class="mk">异常</em>的<em class="mk">子类</em>名称。<code class="fe ns nt nu nv b">except</code>块在遇到<code class="fe ns nt nu nv b">string</code>作为输入时打印出<code class="fe ns nt nu nv b">TypeError</code>。</li><li id="a5af" class="oh oi iq lq b lr oq lu or lx os mb ot mf ou mj om on oo op bi translated"><code class="fe ns nt nu nv b">print(e)</code>:打印出整个错误信息。</li></ul></div><div class="ab cl ov ow hu ox" role="separator"><span class="oy bw bk oz pa pb"/><span class="oy bw bk oz pa pb"/><span class="oy bw bk oz pa"/></div><div class="ij ik il im in"><p id="d0be" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated"><strong class="lq ir">但是如果</strong> <code class="fe ns nt nu nv b"><strong class="lq ir">e</strong></code> <strong class="lq ir">是一个异常类的<em class="mk">对象</em>，我们不应该用类似</strong> <code class="fe ns nt nu nv b"><strong class="lq ir">e.print_something()</strong></code> <strong class="lq ir">的东西吗？</strong></p><p id="6952" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">这是可能的，因为 Python <em class="mk">异常</em>类带有一个名为<code class="fe ns nt nu nv b">__str__()</code>的内置方法。在一个类中定义这个方法可以直接打印出一个类。</p><p id="31c8" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">🛑试试看！不要调用<code class="fe ns nt nu nv b">e</code>，而是调用<code class="fe ns nt nu nv b">e.__str__()</code>来打印错误信息。</p></div><div class="ab cl ov ow hu ox" role="separator"><span class="oy bw bk oz pa pb"/><span class="oy bw bk oz pa pb"/><span class="oy bw bk oz pa"/></div><div class="ij ik il im in"><h2 id="962f" class="ng kx iq bd ky nh pc dn lc nj pd dp lg lx pe nm li mb pf no lk mf pg nq lm nr bi translated">如果我们需要一些定制呢？</h2><p id="74e4" class="pw-post-body-paragraph lo lp iq lq b lr ls jr lt lu lv ju lw lx ly lz ma mb mc md me mf mg mh mi mj ij bi translated">从我们的<code class="fe ns nt nu nv b">calcArea()</code>函数中，我们可以看到<code class="fe ns nt nu nv b">ValueError</code>是一个重复的错误类型——用户输入的是<code class="fe ns nt nu nv b">string</code>而不是数值，因此 Python 无法执行数值运算。如果我们定制<code class="fe ns nt nu nv b">try-except</code>块来适应这种常见的错误类型，并在完全忽略用户的输入之前给用户另一个机会，怎么样？</p><p id="8b9c" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">为此，我们可以专门为<code class="fe ns nt nu nv b">ValueError</code>异常调用一个单独的代码块。在这里我们将检查或验证输入<code class="fe ns nt nu nv b">type</code>以确保它只是<code class="fe ns nt nu nv b">int</code>或<code class="fe ns nt nu nv b">float</code>类型。否则，我们将继续提示用户输入一个数值作为输入。</p><p id="3e99" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">为了简化验证过程，让我们定义一个名为<code class="fe ns nt nu nv b">validate_input()</code>的函数——它将进行检查，如果输入变量是<code class="fe ns nt nu nv b">float</code>类型，则返回<code class="fe ns nt nu nv b">True</code>，否则返回<code class="fe ns nt nu nv b">False</code>状态。</p><pre class="kg kh ki kj gt ny nv nz oa aw ob bi"><span id="7fa8" class="ng kx iq nv b gy oc od l oe of">def validate_input(value):<br/>    try: <br/>        value = float(value)<br/>        return True<br/>    except: return False</span></pre><figure class="kg kh ki kj gt kk"><div class="bz fp l di"><div class="nw nx l"/></div></figure><pre class="kg kh ki kj gt ny nv nz oa aw ob bi"><span id="4ece" class="ng kx iq nv b gy oc od l oe of">calcArea() ran successfully for 5<br/>Area for input 5 = 78.53999999999999 <br/>calcArea() run completed on 2022-03-24 10:36:57.001287<br/><br/>Input data is not numeric type.<br/>Please input a numeric value: 8<br/>Area for input 8 = 201.0624 <br/>calcArea() run completed on 2022-03-24 10:37:00.426775<br/><br/>calcArea() ran successfully for 4<br/>Area for input 4 = 50.2656 <br/>calcArea() run completed on 2022-03-24 10:37:00.426775<br/><br/>calcArea() ran successfully for 8<br/>Area for input 8 = 201.0624 <br/>calcArea() run completed on 2022-03-24 10:37:00.426775<br/><br/>Input data is not numeric type.<br/>Please input a numeric value: k<br/>Please input a numeric value: 999<br/>Area for input 999 = 3135319.9416 <br/>calcArea() run completed on 2022-03-24 10:37:04.927187<br/><br/>calcArea() ran successfully for 0<br/>Area for input 0 = 0.0 <br/>calcArea() run completed on 2022-03-24 10:37:04.927187</span></pre><p id="c352" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">为了定制对<code class="fe ns nt nu nv b">ValueError</code>的响应，我们添加了一个专门的代码块来只捕获<code class="fe ns nt nu nv b">ValueError</code>异常。在代码异常块内部，</p><ul class=""><li id="2a43" class="oh oi iq lq b lr nb lu nc lx oj mb ok mf ol mj om on oo op bi translated">我们正在给用户打印一条消息。</li><li id="57dc" class="oh oi iq lq b lr oq lu or lx os mb ot mf ou mj om on oo op bi translated">然后我们在一个循环中请求一个数字输入，直到输入类型是数字。</li><li id="bed4" class="oh oi iq lq b lr oq lu or lx os mb ot mf ou mj om on oo op bi translated">最后，在收到数字类型输入时，我们再次调用<code class="fe ns nt nu nv b">calcArea()</code>。</li></ul><p id="bef7" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">注意一些事情，</p><p id="fcaa" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">📌我们将<code class="fe ns nt nu nv b">ValueError</code>代码块放在了<code class="fe ns nt nu nv b">Exception</code>代码块的上面。否则，我们的代码永远不会到达<code class="fe ns nt nu nv b">ValueError</code>部分。因为它是 Exception 类的子类，所以它会被<code class="fe ns nt nu nv b">Exception</code>代码块捕获。</p><p id="ce4d" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">📌我们没有在<code class="fe ns nt nu nv b">ValueError</code>代码块中使用<code class="fe ns nt nu nv b">ValueError as e</code>，但是<strong class="lq ir">可以有</strong>。因为我们不需要任何<em class="mk">类</em>属性来打印或用于其他用途，所以我们没有捕获<em class="mk"> TypeError </em>类作为对象。</p><p id="e25f" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">🛑考虑这样一个场景，你可能想要合并其他特定的<em class="mk">异常</em>类型。你将如何整合它们？</p><h1 id="d39e" class="kw kx iq bd ky kz la lb lc ld le lf lg jw lh jx li jz lj ka lk kc ll kd lm ln bi translated">将异常理解为一个类</h1><p id="c130" class="pw-post-body-paragraph lo lp iq lq b lr ls jr lt lu lv ju lw lx ly lz ma mb mc md me mf mg mh mi mj ij bi translated">我在这篇文章中多次提到过<em class="mk">异常</em>是类，但是除了展示一些应用之外，并没有太多的细节。让我们在本节中尝试这样做。</p><blockquote class="ml"><p id="d4bd" class="mm mn iq bd mo mp mq mr ms mt mu mj dk translated"><em class="mv">在 Python 中，所有的</em>异常<em class="mv">都是从被称为</em> <code class="fe ns nt nu nv b"><em class="mv">BaseException</em></code> <em class="mv">的</em>类<em class="mv">中派生出来的。</em></p></blockquote><p id="ecf9" class="pw-post-body-paragraph lo lp iq lq b lr mw jr lt lu mx ju lw lx my lz ma mb mz md me mf na mh mi mj ij bi translated">在<code class="fe ns nt nu nv b">BaseException</code>下面，所有的内置异常被安排成一个层次结构。<code class="fe ns nt nu nv b">BaseException</code>下的四个主要子类是:</p><ul class=""><li id="b466" class="oh oi iq lq b lr nb lu nc lx oj mb ok mf ol mj om on oo op bi translated">系统退出</li><li id="d590" class="oh oi iq lq b lr oq lu or lx os mb ot mf ou mj om on oo op bi translated">键盘中断</li><li id="0178" class="oh oi iq lq b lr oq lu or lx os mb ot mf ou mj om on oo op bi translated">发电机出口</li><li id="65e6" class="oh oi iq lq b lr oq lu or lx os mb ot mf ou mj om on oo op bi translated">例外</li></ul><p id="992b" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">我们通常关心或想要采取行动的异常是<em class="mk">异常</em>子类下的异常。<em class="mk">异常</em>子类又包含几组<em class="mk">子类</em>。下面是 Python 类的部分树层次结构。详情请参考来自 python.org 的官方文件。</p><pre class="kg kh ki kj gt ny nv nz oa aw ob bi"><span id="1b19" class="ng kx iq nv b gy oc od l oe of">BaseException<br/> +-- SystemExit<br/> +-- KeyboardInterrupt<br/> +-- GeneratorExit<br/> +-- Exception<br/>      +-- StopIteration<br/>      +-- StopAsyncIteration<br/>      +-- ArithmeticError<br/>      |    +-- FloatingPointError<br/>      |    +-- OverflowError<br/>      |    +-- ZeroDivisionError<br/>      +-- AssertionError<br/>      +-- AttributeError<br/>      +-- BufferError<br/>      +-- EOFError<br/>      +-- ImportError<br/>      |    +-- ModuleNotFoundError<br/>      +-- LookupError</span></pre><p id="b63a" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">🛑你可以在这些类上运行用于检查公共类层次关系的方法来自己检查上面的层次结构。试试跑步，</p><ul class=""><li id="ec5f" class="oh oi iq lq b lr nb lu nc lx oj mb ok mf ol mj om on oo op bi translated"><code class="fe ns nt nu nv b">print(BaseException.__subclasses__())</code>:你应该看到<code class="fe ns nt nu nv b">BaseException</code>类下的主要子类。</li><li id="e12b" class="oh oi iq lq b lr oq lu or lx os mb ot mf ou mj om on oo op bi translated"><code class="fe ns nt nu nv b">print(issubclass(ValueError, Exception))</code>:你应该看到<code class="fe ns nt nu nv b">True</code>作为返回值，因为<code class="fe ns nt nu nv b">ValueError</code>是<code class="fe ns nt nu nv b">Exception</code>的子类。</li></ul><h1 id="9232" class="kw kx iq bd ky kz la lb lc ld le lf lg jw lh jx li jz lj ka lk kc ll kd lm ln bi translated">实现我们自己的异常</h1><p id="6887" class="pw-post-body-paragraph lo lp iq lq b lr ls jr lt lu lv ju lw lx ly lz ma mb mc md me mf mg mh mi mj ij bi translated">到目前为止，我们只使用了 Python 已经定义的异常。如果我们想要一个进一步定制的异常怎么办？为此，我们可以定义自己的异常类。</p><blockquote class="ml"><p id="f901" class="mm mn iq bd mo mp mq mr ms mt mu mj dk translated"><em class="mv">由于</em>异常<em class="mv">是</em>类<em class="mv">，我们可以像编写常规 Python </em>类<em class="mv">一样编写自己的自定义</em>异常<em class="mv">类。</em></p></blockquote><p id="2a17" class="pw-post-body-paragraph lo lp iq lq b lr mw jr lt lu mx ju lw lx my lz ma mb mz md me mf na mh mi mj ij bi translated">在我们的例子中，假设我们希望将用户输入限制在一个可管理的范围内，这样用户就不能要求程序计算任意大半径的面积。出于演示的目的，假设我们想将其限制在<code class="fe ns nt nu nv b">50</code>英寸以内。</p><p id="ccd4" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">我们可以通过在<code class="fe ns nt nu nv b">calcArea()</code>函数中添加一个<code class="fe ns nt nu nv b">if</code>条件来轻松做到这一点。但是使用<code class="fe ns nt nu nv b">exceptions</code>有一种更好的方法。</p><h1 id="96b6" class="kw kx iq bd ky kz la lb lc ld le lf lg jw lh jx li jz lj ka lk kc ll kd lm ln bi translated">编写自定义异常</h1><p id="524b" class="pw-post-body-paragraph lo lp iq lq b lr ls jr lt lu lv ju lw lx ly lz ma mb mc md me mf mg mh mi mj ij bi translated">对于我们的解决方案，我们将首先定义我们自己的异常类<code class="fe ns nt nu nv b">Above50Error</code>。</p><pre class="kg kh ki kj gt ny nv nz oa aw ob bi"><span id="417b" class="ng kx iq nv b gy oc od l oe of">class Above50Error(Exception):<br/>    def __init__(self, value):            <br/>        Exception.__init__(self)<br/>        self.value = value<br/>        <br/>    def __str__(self):<br/>        return "Input {} is larger than 50 inches".format(self.value)</span></pre><p id="5e9b" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated"><code class="fe ns nt nu nv b">Above50Error</code>异常类被创建为内置<em class="mk">异常</em>异常<em class="mk">类</em>的子类，这样它就继承了所有的属性。</p><ul class=""><li id="03d3" class="oh oi iq lq b lr nb lu nc lx oj mb ok mf ol mj om on oo op bi translated">我们用一个参数初始化它:<code class="fe ns nt nu nv b">value</code>，然后将它存储为一个名为<code class="fe ns nt nu nv b">value</code>的类<em class="mk"> </em>变量。</li><li id="501a" class="oh oi iq lq b lr oq lu or lx os mb ot mf ou mj om on oo op bi translated">然后我们重写从异常类继承的<code class="fe ns nt nu nv b">__str__()</code> <em class="mk">方法</em>来打印出一条定制消息。</li></ul><p id="e4cd" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">注意，要打印出自定义消息，我们可以在初始化<code class="fe ns nt nu nv b">Above50Error</code>时添加一条消息作为参数，并将其传递给<code class="fe ns nt nu nv b">Exception</code>初始化。<code class="fe ns nt nu nv b">Exception</code> <em class="mk">类</em>会将参数作为消息传递并自定义<code class="fe ns nt nu nv b">__str__()</code>方法。但是我们用更长的方式实现它只是为了演示。</p><p id="c9de" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">🛑试试看！修改<code class="fe ns nt nu nv b">Above50Error</code>，使其不需要<code class="fe ns nt nu nv b">__str__()</code>方法来打印消息。</p><p id="6b2a" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">🛑:还有，你能想出一个方法来确认<code class="fe ns nt nu nv b">Above50Error</code>是否真的是<code class="fe ns nt nu nv b">Exception</code>的子类吗？</p><p id="a762" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">要了解更多关于 Python 类和子类关系的知识，你可以查看我的帖子<a class="ae kv" href="https://curious-joe.net/post/2022-03-13-oop-python-inheritance-and-subclass/oop-python-inheritance-subclass/" rel="noopener ugc nofollow" target="_blank">Python 中的面向对象编程——继承和子类</a></p><h2 id="d4fb" class="ng kx iq bd ky nh pc dn lc nj pd dp lg lx pe nm li mb pf no lk mf pg nq lm nr bi translated">实现自定义异常</h2><p id="2e3b" class="pw-post-body-paragraph lo lp iq lq b lr ls jr lt lu lv ju lw lx ly lz ma mb mc md me mf mg mh mi mj ij bi translated">由于<code class="fe ns nt nu nv b">Above50Error</code>是一个自定义异常，所以当我们想要将它注册为异常时，我们需要推动 Python 将其提升为异常。因此，当我们将代码放在一个<code class="fe ns nt nu nv b">try-except</code>代码块中时，它可以将行为捕获为异常。为此，我们使用了<code class="fe ns nt nu nv b">raise</code>关键字。</p><p id="0c9c" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">所以我们修改了<code class="fe ns nt nu nv b">calcArea()</code>函数，添加了一个条件来检查输入值是否高于 50。如果是，它抛出<code class="fe ns nt nu nv b">Above50Error</code>异常，否则继续计算面积。</p><pre class="kg kh ki kj gt ny nv nz oa aw ob bi"><span id="431d" class="ng kx iq nv b gy oc od l oe of">def calcArea(radius):<br/>    pi = 3.1416<br/>    radius = float(radius)<br/>    if radius &gt; 50:<br/>        raise Above50Error(radius)<br/>    else: <br/>        area = pi * radius ** 2<br/>    return area</span></pre><figure class="kg kh ki kj gt kk"><div class="bz fp l di"><div class="nw nx l"/></div></figure><pre class="kg kh ki kj gt ny nv nz oa aw ob bi"><span id="03d4" class="ng kx iq nv b gy oc od l oe of">calcArea() ran successfully for 5<br/>Area for input 5 = 78.53999999999999 <br/>calcArea() run completed on 2022-03-24 10:37:15.619721<br/><br/>calcArea() ran successfully for 5<br/>Area for input 5 = 78.53999999999999 <br/>calcArea() run completed on 2022-03-24 10:37:15.619721<br/><br/>Area couldn't be calculated for 55.<br/>Error type: Above50Error <br/>Error msg: Input 55.0 is larger than 50 inches.<br/>Area for input 55 = None <br/>calcArea() run completed on 2022-03-24 10:37:15.619721<br/><br/>calcArea() ran successfully for 4<br/>Area for input 4 = 50.2656 <br/>calcArea() run completed on 2022-03-24 10:37:15.619721<br/><br/>calcArea() ran successfully for 8<br/>Area for input 8 = 201.0624 <br/>calcArea() run completed on 2022-03-24 10:37:15.619721<br/><br/>Input data is not numeric type.<br/>Please input a numeric value: k<br/>Please input a numeric value: 7<br/>Area for input 7 = 153.9384 <br/>calcArea() run completed on 2022-03-24 10:37:20.308639<br/><br/>calcArea() ran successfully for 0<br/>Area for input 0 = 0.0 <br/>calcArea() run completed on 2022-03-24 10:37:20.308639</span></pre><p id="59f3" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">注意<code class="fe ns nt nu nv b">Exception</code>的 except 代码块是如何捕获我们定制的<em class="mk">异常</em>的。在总结之前，让我们强调一下自定义异常类的一些特性:</p><ul class=""><li id="5b50" class="oh oi iq lq b lr nb lu nc lx oj mb ok mf ol mj om on oo op bi translated">自定义异常类类似于常规的内置异常类。例如，我们可以为<code class="fe ns nt nu nv b">Above50Error</code>创建一个单独的 except 代码块，就像我们为<code class="fe ns nt nu nv b">ValueError</code>所做的那样。试试看！</li><li id="698d" class="oh oi iq lq b lr oq lu or lx os mb ot mf ou mj om on oo op bi translated">此外，由于这些是类，我们可以创建它们自己的子类，以便对错误和异常进行更多的定制。</li></ul><h1 id="4102" class="kw kx iq bd ky kz la lb lc ld le lf lg jw lh jx li jz lj ka lk kc ll kd lm ln bi translated">下一步是什么？</h1><p id="921c" class="pw-post-body-paragraph lo lp iq lq b lr ls jr lt lu lv ju lw lx ly lz ma mb mc md me mf mg mh mi mj ij bi translated">这将是我的 Python 系列中面向对象编程的总结。在这个系列中，我试图解释:</p><ul class=""><li id="79a9" class="oh oi iq lq b lr nb lu nc lx oj mb ok mf ol mj om on oo op bi translated"><a class="ae kv" href="https://curious-joe.net/post/2022-03-09-oop-in-python-what-why/oop-python-what-why/" rel="noopener ugc nofollow" target="_blank">什么是 OOP，为什么要关注它？</a></li><li id="56cb" class="oh oi iq lq b lr oq lu or lx os mb ot mf ou mj om on oo op bi translated"><a class="ae kv" href="https://curious-joe.net/post/2022-03-11-oop-in-python-elements-of-class/oop-python-understanding-class/" rel="noopener ugc nofollow" target="_blank">了解一个类。</a></li><li id="4f2a" class="oh oi iq lq b lr oq lu or lx os mb ot mf ou mj om on oo op bi translated"><a class="ae kv" href="https://curious-joe.net/post/2022-03-13-oop-python-inheritance-and-subclass/oop-python-inheritance-subclass/" rel="noopener ugc nofollow" target="_blank">理解这个概念在子类中的继承和应用。</a></li><li id="3cfe" class="oh oi iq lq b lr oq lu or lx os mb ot mf ou mj om on oo op bi translated"><a class="ae kv" href="https://curious-joe.net/post/2202-03-16-oop-python-variables-in-class/oop-python-inheritance-subclass/" rel="noopener ugc nofollow" target="_blank">在类上下文中理解 Python 变量。</a></li><li id="7468" class="oh oi iq lq b lr oq lu or lx os mb ot mf ou mj om on oo op bi translated">理解 Python 方法。</li></ul><p id="b0e1" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">最后，在这篇博客中，我们深入探讨了 Python 异常，作为 Python 类的一个例子。</p></div><div class="ab cl ov ow hu ox" role="separator"><span class="oy bw bk oz pa pb"/><span class="oy bw bk oz pa pb"/><span class="oy bw bk oz pa"/></div><div class="ij ik il im in"><p id="a791" class="pw-post-body-paragraph lo lp iq lq b lr nb jr lt lu nc ju lw lx nd lz ma mb ne md me mf nf mh mi mj ij bi translated">感谢您阅读这篇文章，希望这个博客系列能让您对 Python 中的面向对象编程有一个初步的了解。在未来的系列文章中，我们将踏上另一段旅程，进入 Python <em class="mk">类</em>的世界，并有更深入的理解。</p></div></div>    
</body>
</html>